import numpy as np

# --- GAME CONFIG ---
NUM_PLAYERS = 5
CARDS_PER_PLAYER = 9
NUM_DECKS = 2
TOTAL_CARDS = 52 * NUM_DECKS

# --- CARD MAPPING ---
FACE_ACE = 0
FACE_2 = 1
FACE_3 = 2
FACE_4 = 3
FACE_5 = 4
FACE_6 = 5
FACE_7 = 6
FACE_8 = 7
FACE_9 = 8
FACE_10 = 9
FACE_JACK = 10
FACE_QUEEN = 11
FACE_KING = 12

POINT_VALUES = {
    FACE_ACE: 1, FACE_2: 2, FACE_3: 3, FACE_4: 4,
    FACE_5: 5, FACE_6: 6, FACE_7: 7, FACE_8: -2,
    FACE_9: 9, FACE_10: 10, FACE_JACK: 10,
    FACE_QUEEN: 10, FACE_KING: 0
}

FACE_STR_MAP = {
    FACE_ACE: "A", FACE_2: "2", FACE_3: "3", FACE_4: "4",
    FACE_5: "5", FACE_6: "6", FACE_7: "7", FACE_8: "8",
    FACE_9: "9", FACE_10: "T", FACE_JACK: "J",
    FACE_QUEEN: "Q", FACE_KING: "K"
}

# --- OBSERVATION SIZES ---
OBS_SIZE = 736
ACTION_SIZE = 10

# --- STAGE CONSTANTS ---
STAGE_ARRANGE = 0
STAGE_FLIP_1 = 1
STAGE_FLIP_2 = 2
STAGE_PLAY_DRAW = 3    
STAGE_PLAY_DISCARD = 4